### ISSUE TITLE
use includes instead

### ISSUE THREAD

**Issue by RamyAlshurafa** [FACG5/reuters-news#20]
https://github.com/FACG5/reuters-news/blob/3a9c4a8efc89d405070a8a85b06458df420e81f3/src/router.js#L13
you can do this instead
```js
else if(url.includes('public')&& url.includes('.'))
```

**Comment by MarwanElkhoudary** [comment]
the method we used does the same purpose

**Comment by RamyAlshurafa** [comment]
@ibraghada @yasminhillis 
take a look here, please!
