### ISSUE TITLE
your API key is generally exposed

### ISSUE THREAD

**Issue by RamyAlshurafa** [FACG5/reuters-news#21]
https://github.com/FACG5/reuters-news/blob/3a9c4a8efc89d405070a8a85b06458df420e81f3/src/server.js#L12
first, that's not required in this week but I need you to think how to protect your secret API key

**Comment by MarwanElkhoudary** [comment]
not required in this week
thank you

**Comment by RamyAlshurafa** [comment]
@ibraghada @yasminhillis
take a look here, please!

**Comment by yasminove** [comment]
Thanks for directing me at this, @RamyAlshurafa. Sorry for what you've been through. I will handle the situation the proper way.

**Comment by MarwanElkhoudary** [comment]
Hello all..
I'm apologize about this situation Mr. Ramy,
Really, i dont mean to offend you..
But I don't write good expression.

‫مُرسل من هاتف Sony Xperia™‎ الذكي الخاص بي

‏

----‏ Yasmin Hillis كتب ----


Thanks for directing me at this, @RamyAlshurafa<https://github.com/RamyAlshurafa>. Sorry for what you've been through. I will handle the situation the proper way.

**Comment by RamyAlshurafa** [comment]
thank you for the interest @yasminhillis .
I mentioned you at the first then I felt like I should give him the excuse for not proper expression.
so I deleted the comment.
 @MarwanElkhoudary don't worry it's ok I appreciate your situation.
